db_file: "bot.db"

bot_url: "https://t.me/pocket_behran_test_bot"

messages:
  responses:
    start: "Привет! Чтобы сохранить ссылку в свой Pocket аккануте, для начала тебе необходимо дать мне на это доступю. Для этого переходи по ссылке:
            %s"
    already_auth: "Ты уже авторизирован. Присылай ссылку, а я ее сохраню!"
    saved_successfully: "Ссылка умпешно сохранена!"
    unknown_command: "Я не знаю такой команды"
  errors:
    default: "Произошла неизвестная ошибка!"
    invalid_url: "Это не валидная ссылка!"
    unauthorized: "Ты не авторищирован! Используй команду /start"
    unable_to_save: "Увы, не удоалсь сохранить ссылку. Попробуй еще раз позже."